-- Auto-generated by auto_prove.py. Do not edit manually.
import Mathlib.Tactic

open BigOperators

namespace AutoProved

-- stmt: theorem t1 : (1:ℕ) + 1 = 2
-- goal:
--   ⊢ 1 + 1 = 2
-- added: 2026-06-05
theorem t1 : (1:ℕ) + 1 = 2 := by
  rfl

-- stmt: theorem t2 (n : ℕ) : n + 0 = n
-- goal:
--   n : ℕ
--   ⊢ n + 0 = n
-- added: 2026-06-05
theorem t2 (n : ℕ) : n + 0 = n := by
  omega

-- stmt: theorem t3 (a b : ℤ) : a + b = b + a
-- goal:
--   a b : ℤ
--   ⊢ a + b = b + a
-- added: 2026-06-05
theorem t3 (a b : ℤ) : a + b = b + a := by
  omega

-- stmt: theorem t4 (a b : ℝ) : (a + b)^2 = a^2 + 2*a*b + b^2
-- goal:
--   a b : ℝ
--   ⊢ (a + b) ^ 2 = a ^ 2 + 2 * a * b + b ^ 2
-- added: 2026-06-05
theorem t4 (a b : ℝ) : (a + b)^2 = a^2 + 2*a*b + b^2 := by
  ring

-- stmt: theorem t5 (a b c : ℕ) : (a + b) + c = a + (b + c)
-- goal:
--   a b c : ℕ
--   ⊢ a + b + c = a + (b + c)
-- added: 2026-06-05
theorem t5 (a b c : ℕ) : (a + b) + c = a + (b + c) := by
  omega

-- stmt: theorem t6 (n : ℕ) : 2 * ∑ k ∈ Finset.range (n + 1), k = n * (n + 1)
-- goal:
--   n : ℕ
--   ⊢ 2 * ∑ k ∈ Finset.range (n + 1), k = n * (n + 1)
-- added: 2026-06-05
theorem t6 (n : ℕ) : 2 * ∑ k ∈ Finset.range (n + 1), k = n * (n + 1) := by
  induction n with
  | zero => simp
  | succ m ih =>
    rw [Finset.sum_range_succ]; nlinarith [ih]

-- stmt: theorem t7 (n : ℕ) : 6 * ∑ k ∈ Finset.range (n + 1), k ^ 2 = n * (n + 1) * (2 * n + 1)
-- goal:
--   n : ℕ
--   ⊢ 6 * ∑ k ∈ Finset.range (n + 1), k ^ 2 = n * (n + 1) * (2 * n + 1)
-- added: 2026-06-05
theorem t7 (n : ℕ) : 6 * ∑ k ∈ Finset.range (n + 1), k ^ 2 = n * (n + 1) * (2 * n + 1) := by
  induction n with
  | zero => simp
  | succ m ih =>
    rw [Finset.sum_range_succ]; nlinarith [ih]

-- stmt: theorem bench_imp_id (P : Prop) : P → P
-- goal:
--   P : Prop
--   ⊢ P → P
-- added: 2026-06-05
theorem bench_imp_id (P : Prop) : P → P := by
  simp

-- stmt: theorem bench_imp_weak (P Q : Prop) : P → Q → P
-- goal:
--   P Q : Prop
--   ⊢ P → Q → P
-- added: 2026-06-05
theorem bench_imp_weak (P Q : Prop) : P → Q → P := by
  tauto

-- stmt: theorem bench_imp_trans (P Q R : Prop) : (P → Q) → (Q → R) → (P → R)
-- goal:
--   P Q R : Prop
--   ⊢ (P → Q) → (Q → R) → P → R
-- added: 2026-06-05
theorem bench_imp_trans (P Q R : Prop) : (P → Q) → (Q → R) → (P → R) := by
  tauto

-- stmt: theorem bench_and_intro (P Q : Prop) (hp : P) (hq : Q) : P ∧ Q
-- goal:
--   P Q : Prop
--   hp : P
--   hq : Q
--   ⊢ P ∧ Q
-- added: 2026-06-05
theorem bench_and_intro (P Q : Prop) (hp : P) (hq : Q) : P ∧ Q := by
  tauto

-- stmt: theorem bench_and_left (P Q : Prop) (h : P ∧ Q) : P
-- goal:
--   P Q : Prop
--   h : P ∧ Q
--   ⊢ P
-- added: 2026-06-05
theorem bench_and_left (P Q : Prop) (h : P ∧ Q) : P := by
  tauto

-- stmt: theorem bench_and_right (P Q : Prop) (h : P ∧ Q) : Q
-- goal:
--   P Q : Prop
--   h : P ∧ Q
--   ⊢ Q
-- added: 2026-06-05
theorem bench_and_right (P Q : Prop) (h : P ∧ Q) : Q := by
  tauto

-- stmt: theorem bench_and_comm (P Q : Prop) : P ∧ Q → Q ∧ P
-- goal:
--   P Q : Prop
--   ⊢ P ∧ Q → Q ∧ P
-- added: 2026-06-05
theorem bench_and_comm (P Q : Prop) : P ∧ Q → Q ∧ P := by
  tauto

-- stmt: theorem bench_or_inl (P Q : Prop) (hp : P) : P ∨ Q
-- goal:
--   P Q : Prop
--   hp : P
--   ⊢ P ∨ Q
-- added: 2026-06-05
theorem bench_or_inl (P Q : Prop) (hp : P) : P ∨ Q := by
  tauto

-- stmt: theorem bench_or_inr (P Q : Prop) (hq : Q) : P ∨ Q
-- goal:
--   P Q : Prop
--   hq : Q
--   ⊢ P ∨ Q
-- added: 2026-06-05
theorem bench_or_inr (P Q : Prop) (hq : Q) : P ∨ Q := by
  tauto

-- stmt: theorem bench_or_comm (P Q : Prop) : P ∨ Q → Q ∨ P
-- goal:
--   P Q : Prop
--   ⊢ P ∨ Q → Q ∨ P
-- added: 2026-06-05
theorem bench_or_comm (P Q : Prop) : P ∨ Q → Q ∨ P := by
  tauto

-- stmt: theorem bench_not_false : ¬False
-- goal:
--   ⊢ ¬False
-- added: 2026-06-05
theorem bench_not_false : ¬False := by
  simp

-- stmt: theorem bench_contrapos (P Q : Prop) : (P → Q) → (¬Q → ¬P)
-- goal:
--   P Q : Prop
--   ⊢ (P → Q) → ¬Q → ¬P
-- added: 2026-06-05
theorem bench_contrapos (P Q : Prop) : (P → Q) → (¬Q → ¬P) := by
  tauto

-- stmt: theorem bench_absurd_ex (P Q : Prop) : P → ¬P → Q
-- goal:
--   P Q : Prop
--   ⊢ P → ¬P → Q
-- added: 2026-06-05
theorem bench_absurd_ex (P Q : Prop) : P → ¬P → Q := by
  tauto

-- stmt: theorem bench_iff_refl (P : Prop) : P ↔ P
-- goal:
--   P : Prop
--   ⊢ P ↔ P
-- added: 2026-06-05
theorem bench_iff_refl (P : Prop) : P ↔ P := by
  rfl

-- stmt: theorem bench_iff_mp (P Q : Prop) (h : P ↔ Q) (hp : P) : Q
-- goal:
--   P Q : Prop
--   h : P ↔ Q
--   hp : P
--   ⊢ Q
-- added: 2026-06-05
theorem bench_iff_mp (P Q : Prop) (h : P ↔ Q) (hp : P) : Q := by
  tauto

-- stmt: theorem bench_demorgan (P Q : Prop) : ¬(P ∨ Q) → ¬P ∧ ¬Q
-- goal:
--   P Q : Prop
--   ⊢ ¬(P ∨ Q) → ¬P ∧ ¬Q
-- added: 2026-06-05
theorem bench_demorgan (P Q : Prop) : ¬(P ∨ Q) → ¬P ∧ ¬Q := by
  simp

-- stmt: theorem bench_sq_sum (a b : ℝ) : (a + b)^2 = a^2 + 2*a*b + b^2
-- goal:
--   a b : ℝ
--   ⊢ (a + b) ^ 2 = a ^ 2 + 2 * a * b + b ^ 2
-- added: 2026-06-05
theorem bench_sq_sum (a b : ℝ) : (a + b)^2 = a^2 + 2*a*b + b^2 := by
  ring

-- stmt: theorem bench_sq_diff (a b : ℝ) : (a - b)^2 = a^2 - 2*a*b + b^2
-- goal:
--   a b : ℝ
--   ⊢ (a - b) ^ 2 = a ^ 2 - 2 * a * b + b ^ 2
-- added: 2026-06-05
theorem bench_sq_diff (a b : ℝ) : (a - b)^2 = a^2 - 2*a*b + b^2 := by
  ring

-- stmt: theorem bench_diff_sq (a b : ℝ) : (a + b) * (a - b) = a^2 - b^2
-- goal:
--   a b : ℝ
--   ⊢ (a + b) * (a - b) = a ^ 2 - b ^ 2
-- added: 2026-06-05
theorem bench_diff_sq (a b : ℝ) : (a + b) * (a - b) = a^2 - b^2 := by
  ring

-- stmt: theorem bench_cube_sum (a b : ℝ) : (a + b)^3 = a^3 + 3*a^2*b + 3*a*b^2 + b^3
-- goal:
--   a b : ℝ
--   ⊢ (a + b) ^ 3 = a ^ 3 + 3 * a ^ 2 * b + 3 * a * b ^ 2 + b ^ 3
-- added: 2026-06-05
theorem bench_cube_sum (a b : ℝ) : (a + b)^3 = a^3 + 3*a^2*b + 3*a*b^2 + b^3 := by
  ring

-- stmt: theorem bench_nat_comm (a b : ℕ) : a + b = b + a
-- goal:
--   a b : ℕ
--   ⊢ a + b = b + a
-- added: 2026-06-05
theorem bench_nat_comm (a b : ℕ) : a + b = b + a := by
  omega

-- stmt: theorem bench_nat_assoc (a b c : ℕ) : (a + b) + c = a + (b + c)
-- goal:
--   a b c : ℕ
--   ⊢ a + b + c = a + (b + c)
-- added: 2026-06-05
theorem bench_nat_assoc (a b c : ℕ) : (a + b) + c = a + (b + c) := by
  omega

-- stmt: theorem bench_nat_le (n : ℕ) : n ≤ n + 1
-- goal:
--   n : ℕ
--   ⊢ n ≤ n + 1
-- added: 2026-06-05
theorem bench_nat_le (n : ℕ) : n ≤ n + 1 := by
  omega

-- stmt: theorem bench_int_linarith (a b : ℤ) (h1 : a ≤ b) (h2 : b ≤ a) : a = b
-- goal:
--   a b : ℤ
--   h1 : a ≤ b
--   h2 : b ≤ a
--   ⊢ a = b
-- added: 2026-06-05
theorem bench_int_linarith (a b : ℤ) (h1 : a ≤ b) (h2 : b ≤ a) : a = b := by
  omega

-- stmt: theorem bench_sum_gauss (n : ℕ) : 2 * ∑ k ∈ Finset.range (n + 1), k = n * (n + 1)
-- goal:
--   n : ℕ
--   ⊢ 2 * ∑ k ∈ Finset.range (n + 1), k = n * (n + 1)
-- added: 2026-06-05
theorem bench_sum_gauss (n : ℕ) : 2 * ∑ k ∈ Finset.range (n + 1), k = n * (n + 1) := by
  induction n with
    | zero => simp
    | succ m ih =>
      rw [Finset.sum_range_succ]; nlinarith [ih]

-- stmt: theorem bench_sum_sq (n : ℕ) : 6 * ∑ k ∈ Finset.range (n + 1), k ^ 2 = n * (n + 1) * (2 * n + 1)
-- goal:
--   n : ℕ
--   ⊢ 6 * ∑ k ∈ Finset.range (n + 1), k ^ 2 = n * (n + 1) * (2 * n + 1)
-- added: 2026-06-05
theorem bench_sum_sq (n : ℕ) : 6 * ∑ k ∈ Finset.range (n + 1), k ^ 2 = n * (n + 1) * (2 * n + 1) := by
  induction n with
    | zero => simp
    | succ m ih =>
      rw [Finset.sum_range_succ]; nlinarith [ih]

-- stmt: theorem bench_hard_prime_inf : ∀ n : ℕ, ∃ p, n ≤ p ∧ Nat.Prime p
-- goal:
--   ⊢ ∀ (n : ℕ), ∃ p, n ≤ p ∧ Nat.Prime p
-- added: 2026-06-05
theorem bench_hard_prime_inf : ∀ n : ℕ, ∃ p, n ≤ p ∧ Nat.Prime p := by
  exact fun n => Nat.exists_infinite_primes n

-- stmt: theorem bench_hard_sqrt (a : ℝ) (ha : 0 ≤ a) : Real.sqrt (a ^ 2) = a
-- goal:
--   a : ℝ
--   ha : 0 ≤ a
--   ⊢ √(a ^ 2) = a
-- added: 2026-06-06
theorem bench_hard_sqrt (a : ℝ) (ha : 0 ≤ a) : Real.sqrt (a ^ 2) = a := by
  exact Real.sqrt_sq ha

-- stmt: theorem bench_hard_cont_comp (f g : ℝ → ℝ) (hf : Continuous f) (hg : Continuous g) : Continuous (f ∘ g)
-- goal:
--   f g : ℝ → ℝ
--   hf : Continuous f
--   hg : Continuous g
--   ⊢ Continuous (f ∘ g)
-- added: 2026-06-06
theorem bench_hard_cont_comp (f g : ℝ → ℝ) (hf : Continuous f) (hg : Continuous g) : Continuous (f ∘ g) := by
  fun_prop

-- stmt: theorem bench_hard_irrational_sqrt2 : Irrational (Real.sqrt 2)
-- goal:
--   ⊢ Irrational √2
-- added: 2026-06-06
theorem bench_hard_irrational_sqrt2 : Irrational (Real.sqrt 2) := by
  exact irrational_sqrt_two

-- stmt: theorem bench_hard_emod (a b c : ℤ) (h : c ∣ b) : a % b % c = a % c
-- goal:
--   a b c : ℤ
--   h : c ∣ b
--   ⊢ a % b % c = a % c
-- added: 2026-06-06
theorem bench_hard_emod (a b c : ℤ) (h : c ∣ b) : a % b % c = a % c := by
  exact Int.emod_emod_of_dvd a h

-- stmt: theorem sq_sum (a b : ℝ) : (a + b)^2 = a^2 + 2*a*b + b^2
-- goal:
--   a b : ℝ
--   ⊢ (a + b) ^ 2 = a ^ 2 + 2 * a * b + b ^ 2
-- added: 2026-06-07
theorem sq_sum (a b : ℝ) : (a + b)^2 = a^2 + 2*a*b + b^2 := by
  ring

-- stmt: theorem sq_diff (a b : ℝ) : (a - b)^2 = a^2 - 2*a*b + b^2
-- goal:
--   a b : ℝ
--   ⊢ (a - b) ^ 2 = a ^ 2 - 2 * a * b + b ^ 2
-- added: 2026-06-07
theorem sq_diff (a b : ℝ) : (a - b)^2 = a^2 - 2*a*b + b^2 := by
  ring

-- stmt: theorem mul_sum_diff (a b : ℝ) : (a + b) * (a - b) = a^2 - b^2
-- goal:
--   a b : ℝ
--   ⊢ (a + b) * (a - b) = a ^ 2 - b ^ 2
-- added: 2026-06-07
theorem mul_sum_diff (a b : ℝ) : (a + b) * (a - b) = a^2 - b^2 := by
  ring

-- stmt: theorem cube_sum (a b : ℝ) : (a + b)^3 = a^3 + 3*a^2*b + 3*a*b^2 + b^3
-- goal:
--   a b : ℝ
--   ⊢ (a + b) ^ 3 = a ^ 3 + 3 * a ^ 2 * b + 3 * a * b ^ 2 + b ^ 3
-- added: 2026-06-07
theorem cube_sum (a b : ℝ) : (a + b)^3 = a^3 + 3*a^2*b + 3*a*b^2 + b^3 := by
  ring

-- stmt: theorem cube_diff (a b : ℝ) : (a - b)^3 = a^3 - 3*a^2*b + 3*a*b^2 - b^3
-- goal:
--   a b : ℝ
--   ⊢ (a - b) ^ 3 = a ^ 3 - 3 * a ^ 2 * b + 3 * a * b ^ 2 - b ^ 3
-- added: 2026-06-07
theorem cube_diff (a b : ℝ) : (a - b)^3 = a^3 - 3*a^2*b + 3*a*b^2 - b^3 := by
  ring

-- stmt: theorem factor_diff_sq (a b : ℝ) : a^2 - b^2 = (a + b) * (a - b)
-- goal:
--   a b : ℝ
--   ⊢ a ^ 2 - b ^ 2 = (a + b) * (a - b)
-- added: 2026-06-07
theorem factor_diff_sq (a b : ℝ) : a^2 - b^2 = (a + b) * (a - b) := by
  ring

end AutoProved
