from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
from datetime import date
from pathlib import Path

WORKDIR = Path(os.environ.get("LEAN_WORKDIR", Path(__file__).parent.parent)).resolve()
LEAN_DB_FILE = WORKDIR / "LeanMathAtlas" / "ProvedTheorems.lean"
AUTO_PROVED_DIR = WORKDIR / "LeanMathAtlas" / "AutoProved"
INDEX_FILE = WORKDIR / ".proof_index.json"


def resolve_lake() -> str:
    """Find lake even when the user's shell PATH is not inherited by Python."""
    candidates = [
        os.environ.get("LEAN_LAKE"),
        shutil.which("lake"),
        str(Path.home() / ".elan" / "bin" / "lake"),
    ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return candidate
    return "lake"


def load_index() -> dict:
    if INDEX_FILE.exists():
        return json.loads(INDEX_FILE.read_text())
    return {}


def save_index(index: dict):
    INDEX_FILE.write_text(json.dumps(index, ensure_ascii=False, indent=2))


def cache_key(stmt: str) -> str:
    return hashlib.sha256(stmt.strip().encode()).hexdigest()[:16]


def extract_preamble(lean_file: Path) -> str:
    """Extract open/variable lines from a .lean file as REPL preamble."""
    lines = lean_file.read_text(encoding="utf-8").splitlines()
    preamble = []
    for line in lines:
        s = line.strip()
        if s.startswith("open ") or s.startswith("variable ") or s.startswith("set_option "):
            preamble.append(s)
        elif s.startswith("theorem ") or s.startswith("def ") or s.startswith("lemma "):
            break
    return "\n".join(preamble)


def lean_name_from(stmt: str) -> str:
    """'theorem foo ...' → 'foo'; otherwise generate from hash."""
    m = re.match(r"^theorem\s+(\S+)", stmt.strip())
    return m.group(1) if m else f"proved_{cache_key(stmt)[:8]}"


def theorem_module_stem(lean_name: str) -> str:
    stem = re.sub(r"[^A-Za-z0-9_]", "_", lean_name)
    if not stem or stem[0].isdigit():
        stem = f"proved_{stem}"
    return stem


def theorem_module_name(lean_name: str) -> str:
    return f"LeanMathAtlas.AutoProved.{theorem_module_stem(lean_name)}"


def theorem_file_path(lean_name: str) -> Path:
    return AUTO_PROVED_DIR / f"{theorem_module_stem(lean_name)}.lean"


def ensured_proof_entry(index_value) -> str | None:
    if isinstance(index_value, dict):
        lean_name = index_value.get("lean_name")
    elif isinstance(index_value, str):
        lean_name = index_value
    else:
        return None
    if not lean_name:
        return None
    return lean_name if theorem_file_path(lean_name).exists() else None


def stmt_body(stmt: str) -> str:
    """'theorem foo (args) : T' → '(args) : T'"""
    return re.sub(r"^theorem\s+\S+", "", stmt.strip()).strip()


def tactic_block(tactic: str) -> str:
    """Indent a tactic string for use inside a `by` block."""
    lines = tactic.split("\n")
    if len(lines) == 1:
        return f"  {tactic}"
    return "\n".join(f"  {line}" for line in lines)


def ensure_lean_db():
    AUTO_PROVED_DIR.mkdir(parents=True, exist_ok=True)
    if not LEAN_DB_FILE.exists():
        LEAN_DB_FILE.write_text(
            "-- Auto-generated by auto_prove.py. Do not edit manually.\n"
            "import Mathlib\n\n"
            "namespace AutoProved\n\n"
            "end AutoProved\n",
            encoding="utf-8",
        )


def build_proved_theorems() -> tuple[bool, str]:
    build = subprocess.run(
        [resolve_lake(), "build", "LeanMathAtlas.ProvedTheorems"],
        cwd=WORKDIR,
        capture_output=True,
        text=True,
    )
    details = (build.stdout or "").strip()
    if build.stderr:
        details = f"{details}\n{build.stderr.strip()}".strip()
    return build.returncode == 0, details


def append_to_lean_db(stmt: str, tactic: str, goal: str, lean_name: str,
                      preamble: str = "") -> tuple[Path, str, bool]:
    ensure_lean_db()
    theorem_path = theorem_file_path(lean_name)
    import_stmt = f"import {theorem_module_name(lean_name)}"
    if theorem_path.exists():
        print(f"  [skip-dup] {theorem_path.name} already exists")
        return theorem_path, import_stmt, False
    goal_commented = "\n".join(f"--   {line}" for line in goal.split("\n"))
    theorem_parts = ["import Mathlib"]
    if preamble:
        theorem_parts.append(preamble)
    theorem_parts.append(
        "namespace AutoProved\n"
        f"-- stmt: {stmt}\n"
        f"-- goal:\n{goal_commented}\n"
        f"-- added: {date.today()}\n"
        f"theorem {lean_name} {stmt_body(stmt)} := by\n"
        f"{tactic_block(tactic)}\n"
        "\nend AutoProved\n"
    )
    theorem_path.write_text("\n\n".join(part for part in theorem_parts if part) + "\n", encoding="utf-8")

    content = LEAN_DB_FILE.read_text(encoding="utf-8")
    if import_stmt not in content:
        lines = content.splitlines()
        insert_at = 0
        for i, line in enumerate(lines):
            if line.startswith("import "):
                insert_at = i + 1
        lines.insert(insert_at, import_stmt)
        LEAN_DB_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return theorem_path, import_stmt, True


def rollback_lean_db_append(theorem_path: Path, import_stmt: str):
    if theorem_path.exists():
        theorem_path.unlink()
    if LEAN_DB_FILE.exists():
        lines = [
            line
            for line in LEAN_DB_FILE.read_text(encoding="utf-8").splitlines()
            if line.strip() != import_stmt
        ]
        LEAN_DB_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def persist_proof(stmt: str, proof: str, goal: str, lean_name: str, preamble: str,
                  index: dict, use_proved: bool):
    theorem_path, import_stmt, created = append_to_lean_db(
        stmt, proof, goal, lean_name, preamble=preamble
    )
    if created and use_proved:
        ok, details = build_proved_theorems()
        if not ok:
            rollback_lean_db_append(theorem_path, import_stmt)
            raise RuntimeError(
                "Saved proof would break LeanMathAtlas.ProvedTheorems in --use-proved mode.\n"
                f"Rolled back {theorem_path.relative_to(WORKDIR)}.\n"
                f"{details}"
            )
    index[cache_key(stmt)] = {"lean_name": lean_name}
