#!/usr/bin/env python3
"""
Lean 4 automated theorem prover.
- Accumulates proofs in ProvedTheorems.lean (correctness guaranteed by the Lean compiler)
- .proof_index.json for fast lookup (hash → theorem name)
- Interactive REPL: breaks immediately on the first successful tactic
- Rule-based tactic filtering: narrows candidates from the goal string
- Iterative proof search: BFS over tactic sequences via REPL tactic mode (time-limited)
"""

from __future__ import annotations
import subprocess, json, re, sys, time, os, hashlib, shutil
from collections import deque
from datetime import date
from pathlib import Path

WORKDIR        = Path(os.environ.get("LEAN_WORKDIR", Path(__file__).parent.parent)).resolve()
SEP            = "\n\n"
LEAN_DB_FILE   = WORKDIR / "LeanMathAtlas" / "ProvedTheorems.lean"
AUTO_PROVED_DIR = WORKDIR / "LeanMathAtlas" / "AutoProved"
INDEX_FILE     = WORKDIR / ".proof_index.json"


def resolve_lake() -> str:
    """Find lake even when the user's shell PATH is not inherited by Python."""
    candidates = [
        os.environ.get("LEAN_LAKE"),
        shutil.which("lake"),
        str(Path.home() / ".elan" / "bin" / "lake"),
    ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return candidate
    return "lake"


REPL_CMD       = [resolve_lake(), "exe", "repl"]

# ────────────────────────────────────────────────
# Index (fast lookup)
# ────────────────────────────────────────────────

def load_index() -> dict:
    if INDEX_FILE.exists():
        return json.loads(INDEX_FILE.read_text())
    return {}

def save_index(index: dict):
    INDEX_FILE.write_text(json.dumps(index, ensure_ascii=False, indent=2))

def cache_key(stmt: str) -> str:
    return hashlib.sha256(stmt.strip().encode()).hexdigest()[:16]

def extract_preamble(lean_file: Path) -> str:
    """Extract open/variable lines from a .lean file as REPL preamble."""
    lines = lean_file.read_text(encoding="utf-8").splitlines()
    preamble = []
    for line in lines:
        s = line.strip()
        if s.startswith("open ") or s.startswith("variable ") or s.startswith("set_option "):
            preamble.append(s)
        elif s.startswith("theorem ") or s.startswith("def ") or s.startswith("lemma "):
            break
    return "\n".join(preamble)

# ────────────────────────────────────────────────
# Writing to ProvedTheorems.lean
# ────────────────────────────────────────────────

def lean_name_from(stmt: str) -> str:
    """'theorem foo ...' → 'foo'; otherwise generate from hash."""
    m = re.match(r"^theorem\s+(\S+)", stmt.strip())
    return m.group(1) if m else f"proved_{cache_key(stmt)[:8]}"


def theorem_module_stem(lean_name: str) -> str:
    stem = re.sub(r"[^A-Za-z0-9_]", "_", lean_name)
    if not stem or stem[0].isdigit():
        stem = f"proved_{stem}"
    return stem


def theorem_module_name(lean_name: str) -> str:
    return f"LeanMathAtlas.AutoProved.{theorem_module_stem(lean_name)}"


def theorem_file_path(lean_name: str) -> Path:
    return AUTO_PROVED_DIR / f"{theorem_module_stem(lean_name)}.lean"


def ensured_proof_entry(index_value) -> str | None:
    if isinstance(index_value, dict):
        lean_name = index_value.get("lean_name")
    elif isinstance(index_value, str):
        lean_name = index_value
    else:
        return None
    if not lean_name:
        return None
    return lean_name if theorem_file_path(lean_name).exists() else None

def stmt_body(stmt: str) -> str:
    """'theorem foo (args) : T' → '(args) : T'"""
    return re.sub(r"^theorem\s+\S+", "", stmt.strip()).strip()

def tactic_block(tactic: str) -> str:
    """Indent a tactic string for use inside a `by` block."""
    lines = tactic.split("\n")
    if len(lines) == 1:
        return f"  {tactic}"
    # Multi-line tactics (induction, etc.) — indent every line
    return "\n".join(f"  {l}" for l in lines)

def ensure_lean_db():
    AUTO_PROVED_DIR.mkdir(parents=True, exist_ok=True)
    if not LEAN_DB_FILE.exists():
        LEAN_DB_FILE.write_text(
            "-- Auto-generated by auto_prove.py. Do not edit manually.\n"
            "import Mathlib\n\n"
            "namespace AutoProved\n\n"
            "end AutoProved\n",
            encoding="utf-8",
        )


def build_proved_theorems() -> tuple[bool, str]:
    build = subprocess.run(
        [resolve_lake(), "build", "LeanMathAtlas.ProvedTheorems"],
        cwd=WORKDIR, capture_output=True, text=True
    )
    details = (build.stdout or "").strip()
    if build.stderr:
        details = f"{details}\n{build.stderr.strip()}".strip()
    return build.returncode == 0, details


def current_db_imports() -> list[str]:
    if not LEAN_DB_FILE.exists():
        return []
    imports = []
    for line in LEAN_DB_FILE.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("import LeanMathAtlas.AutoProved."):
            imports.append(s)
    return imports


def append_to_lean_db(stmt: str, tactic: str, goal: str, lean_name: str,
                      preamble: str = "") -> tuple[Path, str, bool]:
    ensure_lean_db()
    theorem_path = theorem_file_path(lean_name)
    import_stmt = f"import {theorem_module_name(lean_name)}"
    if theorem_path.exists():
        print(f"  [skip-dup] {theorem_path.name} already exists")
        return theorem_path, import_stmt, False
    goal_commented = "\n".join(f"--   {line}" for line in goal.split("\n"))
    theorem_imports = ["import Mathlib"]
    theorem_parts = ["\n".join(theorem_imports)]
    if preamble:
        theorem_parts.append(preamble)
    theorem_parts.append(
        "namespace AutoProved\n"
        f"-- stmt: {stmt}\n"
        f"-- goal:\n{goal_commented}\n"
        f"-- added: {date.today()}\n"
        f"theorem {lean_name} {stmt_body(stmt)} := by\n"
        f"{tactic_block(tactic)}\n"
        "\nend AutoProved\n"
    )
    theorem_path.write_text("\n\n".join(part for part in theorem_parts if part) + "\n", encoding="utf-8")

    content = LEAN_DB_FILE.read_text(encoding="utf-8")
    if import_stmt not in content:
        lines = content.splitlines()
        insert_at = 0
        for i, line in enumerate(lines):
            if line.startswith("import "):
                insert_at = i + 1
        lines.insert(insert_at, import_stmt)
        LEAN_DB_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return theorem_path, import_stmt, True


def rollback_lean_db_append(theorem_path: Path, import_stmt: str):
    if theorem_path.exists():
        theorem_path.unlink()
    if LEAN_DB_FILE.exists():
        lines = [line for line in LEAN_DB_FILE.read_text(encoding="utf-8").splitlines()
                 if line.strip() != import_stmt]
        LEAN_DB_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def persist_proof(stmt: str, proof: str, goal: str, lean_name: str, preamble: str,
                  index: dict, use_proved: bool):
    theorem_path, import_stmt, created = append_to_lean_db(
        stmt, proof, goal, lean_name, preamble=preamble
    )
    if created and use_proved:
        ok, details = build_proved_theorems()
        if not ok:
            rollback_lean_db_append(theorem_path, import_stmt)
            raise RuntimeError(
                "Saved proof would break LeanMathAtlas.ProvedTheorems in --use-proved mode.\n"
                f"Rolled back {theorem_path.relative_to(WORKDIR)}.\n"
                f"{details}"
            )
    index[cache_key(stmt)] = {"lean_name": lean_name}

# ────────────────────────────────────────────────
# Interactive REPL session
# ────────────────────────────────────────────────

class ReplSession:
    def __init__(self):
        self.proc = subprocess.Popen(
            REPL_CMD, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL, cwd=WORKDIR
        )

    def send(self, cmd: dict) -> dict:
        payload = json.dumps(cmd) + SEP
        self.proc.stdin.write(payload.encode())
        self.proc.stdin.flush()
        return self._read_response()

    def _read_response(self) -> dict:
        lines = []
        while True:
            line = self.proc.stdout.readline().decode()
            if line in ("\n", ""):
                if lines:
                    block = "".join(lines).strip()
                    try:
                        return json.loads(block)
                    except json.JSONDecodeError:
                        lines = []
                if line == "":
                    return {}
            else:
                lines.append(line)

    def close(self):
        try:
            self.proc.stdin.close()
        except BrokenPipeError:
            pass
        self.proc.wait()


def prepare_proof_env(dry_run: bool = False, preamble: str = "", use_proved: bool = False) -> tuple[ReplSession, int]:
    """Create a REPL session and return (session, base_env) for theorem proving."""
    if use_proved and not dry_run:
        ok, details = build_proved_theorems()
        if not ok:
            raise RuntimeError(
                "LeanMathAtlas.ProvedTheorems failed to build before proof search.\n"
                f"{details}"
            )

    session = ReplSession()
    _load_proved = use_proved and not dry_run
    print("  [repl] Loading Mathlib + ProvedTheorems (~80s)..." if _load_proved else "  [repl] Loading Mathlib (~80s)...")
    imports = "import Mathlib\nimport LeanMathAtlas.ProvedTheorems" if _load_proved else "import Mathlib"
    resp = session.send({"cmd": imports})
    if has_error(resp):
        session.close()
        raise RuntimeError(
            "Failed to import the Lean environment for proof search.\n"
            f"{format_repl_errors(resp)}"
        )
    env0 = resp.get("env", 0)
    open_cmd = "open BigOperators AutoProved" if _load_proved else "open BigOperators"
    resp = session.send({"cmd": open_cmd, "env": env0})
    if has_error(resp):
        session.close()
        raise RuntimeError(
            "Failed to open the Lean proof environment.\n"
            f"{format_repl_errors(resp)}"
        )
    env1 = resp.get("env", env0)
    resp = session.send({"cmd": "open scoped Nat", "env": env1})
    if has_error(resp):
        session.close()
        raise RuntimeError(
            "Failed to enable scoped Nat notations.\n"
            f"{format_repl_errors(resp)}"
        )
    env2 = resp.get("env", env0)
    if preamble:
        resp = session.send({"cmd": preamble, "env": env2})
        if has_error(resp):
            session.close()
            raise RuntimeError(
                "Failed to load the theorem preamble into the REPL.\n"
                f"{format_repl_errors(resp)}"
            )
    return session, resp.get("env", env2)

# ────────────────────────────────────────────────
# Tactic candidates
# ────────────────────────────────────────────────

SIMPLE_TACTICS = [
    "rfl", "ring", "omega", "simp", "norm_num",
    "decide", "tauto", "linarith", "nlinarith", "aesop",
    "fun_prop",
    "simp [*]", "simp_all", "push_cast; ring", "push_cast; omega",
    "norm_cast", "norm_cast; ring", "norm_cast; omega",
    "linear_combination",
]

# Inner product space / normed space (InnerProductSpace ℝ E goals)
INNER_PRODUCT_TACTICS = [
    # Commutativity: ⟪x, y⟫ = ⟪y, x⟫
    # real_inner_comm _ _ : inner ℝ ?b ?a = inner ℝ ?a ?b (Lean unifies ? from goal)
    "exact real_inner_comm _ _",
    "exact (real_inner_comm _ _).symm",
    # inner_comm for real field: ⟪x,y⟫_ℝ = conj ⟪y,x⟫_ℝ = ⟪y,x⟫_ℝ
    "exact inner_comm (𝕜 := ℝ) _ _",
    "simp only [inner_comm (𝕜 := ℝ)]",
    # Linearity
    "exact inner_add_left _ _ _",
    "exact inner_add_right _ _ _",
    "exact inner_smul_left _ _ _",
    "exact inner_smul_right _ _ _",
    # Positivity / self inner product
    "exact real_inner_self_nonneg",
    "exact inner_self_eq_zero",
    "exact real_inner_self_eq_norm_sq _",
    # Norm
    "exact norm_smul _ _",
    # Broad simp: real_inner_comm は交換律ループを避けるため除外
    "simp [inner_add_left, inner_add_right, inner_smul_left, inner_smul_right, inner_self_eq_zero, real_inner_self_eq_norm_sq, norm_smul]",
    "simp [inner_smul_left]",
    "simp [inner_smul_right]",
    "simp [real_inner_self_eq_norm_sq]",
    # EuclideanSpace concrete basis vectors
    "simp [EuclideanSpace.inner_single_left, EuclideanSpace.inner_single_right]",
    "simp [EuclideanSpace.norm_single]",
    # Cauchy-Schwarz squared: ⟪x,y⟫² ≤ ⟪x,x⟫ * ⟪y,y⟫
    "have h := abs_real_inner_le_norm _ _\n  have hx := real_inner_self_eq_norm_sq _\n  have hy := real_inner_self_eq_norm_sq _\n  nlinarith [sq_abs (inner (𝕜 := ℝ) _ _), abs_nonneg (inner (𝕜 := ℝ) _ _), mul_pow ‖_‖ ‖_‖ 2]",
]

# Trigonometric double/half-angle templates (open Real context assumed)
TRIG_DOUBLE_TACTICS = [
    # cos_two_mul は Mathlib の標準名 (cos_double はローカル定義のため REPL 不可)
    "rw [cos_two_mul]; linarith [sin_sq_add_cos_sq _]",
    "rw [Real.cos_two_mul]; linarith [Real.sin_sq_add_cos_sq _]",
    "rw [cos_two_mul]; nlinarith [sin_sq_add_cos_sq _]",
    "rw [Real.cos_two_mul]; nlinarith [Real.sin_sq_add_cos_sq _]",
    "simp [cos_two_mul, sin_sq_add_cos_sq]",
    "simp [Real.cos_two_mul, Real.sin_sq_add_cos_sq]",
]

# Complex number templates (open Complex context assumed)
COMPLEX_TACTICS = [
    # normSq
    "simp [normSq_apply, sq]",
    "simp [Complex.normSq_apply, sq]",
    "rw [normSq_apply]; ring",
    # de Moivre: (exp(θ*I))^n = exp(n*θ*I)
    "rw [← exp_nat_mul]; congr 1; ring",
    "rw [← Complex.exp_nat_mul]; congr 1; ring",
    "simp [← exp_nat_mul, mul_comm, mul_assoc]",
    # exp of imaginary
    "simp [exp_mul_I, exp_add]",
]

INDUCTION_TACTICS = [
    "induction n with\n  | zero => simp\n  | succ m ih => omega",
    "induction n with\n  | zero => simp\n  | succ m ih => ring",
    "induction n with\n  | zero => simp\n  | succ m ih => linarith",
    "induction n with\n  | zero => simp\n  | succ m ih => nlinarith [ih]",
    "induction n with\n  | zero => simp\n  | succ m ih =>\n    rw [Finset.sum_range_succ]; omega",
    "induction n with\n  | zero => simp\n  | succ m ih =>\n    rw [Finset.sum_range_succ]; nlinarith [ih]",
    "induction n with\n  | zero => simp\n  | succ m ih =>\n    rw [Finset.sum_range_succ, mul_add, ih]; ring",
]

ALL_TACTICS = SIMPLE_TACTICS + INDUCTION_TACTICS

# Search tactics: tried last as fallback; proof is extracted from "Try this:" message
SEARCH_TACTICS = ["exact?", "simp?"]

# HasDerivAt-specific one-shot templates (tried before BFS for derivative goals)
DERIV_TEMPLATES = [
    # scalar multiple: c * sin/cos/exp
    "exact (Real.hasDerivAt_sin _).const_mul _",
    "exact (Real.hasDerivAt_cos _).const_mul _",
    "exact (Real.hasDerivAt_exp _).const_mul _",
    # negation
    "exact (Real.hasDerivAt_sin _).neg",
    "exact (Real.hasDerivAt_cos _).neg",
    # chain rule: f(c * x) — comp gives g'*f', goal may have f'*g' (mul_comm)
    "exact (Real.hasDerivAt_sin _).comp _ ((hasDerivAt_id _).const_mul _)",
    "exact (Real.hasDerivAt_cos _).comp _ ((hasDerivAt_id _).const_mul _)",
    # convert absorbs both function-form and mul_comm mismatches
    "have h := (Real.hasDerivAt_sin _).comp _ ((hasDerivAt_id _).const_mul _)\n  convert h using 1\n  ring",
    "have h := (Real.hasDerivAt_cos _).comp _ ((hasDerivAt_id _).const_mul _)\n  convert h using 1\n  ring",
    # convert using 2 — allows deeper structural mismatches than using 1
    "have h := (Real.hasDerivAt_sin _).comp _ ((hasDerivAt_id _).const_mul _)\n  convert h using 2\n  ring",
    "have h := (Real.hasDerivAt_cos _).comp _ ((hasDerivAt_id _).const_mul _)\n  convert h using 2\n  ring",
    # ring_nf normalises the derivative expression before exact: absorbs mul_comm without convert
    "ring_nf\n  exact (Real.hasDerivAt_sin _).comp _ ((hasDerivAt_id _).const_mul _)",
    "ring_nf\n  exact (Real.hasDerivAt_cos _).comp _ ((hasDerivAt_id _).const_mul _)",
    # explicit two-have pattern (mirrors Derivatives.lean proof style)
    "have hf := (hasDerivAt_id _).const_mul _\n  have hg := Real.hasDerivAt_sin _\n  have h := hg.comp _ hf\n  convert h using 1\n  ring",
    "have hf := (hasDerivAt_id _).const_mul _\n  have hg := Real.hasDerivAt_cos _\n  have h := hg.comp _ hf\n  convert h using 1\n  ring",
    "have hf := (hasDerivAt_id _).const_mul _\n  have hg := Real.hasDerivAt_sin _\n  have h := hg.comp _ hf\n  convert h using 2\n  ring",
    # simp [Function.comp, id] unwraps ∘ notation; norm_num simplifies 2*1→2;
    # then convert + ring handles the remaining mul_comm mismatch.
    "have hf := (hasDerivAt_id _).const_mul _\n  have hg := Real.hasDerivAt_sin _\n  have h := hg.comp _ hf\n  simp only [Function.comp, id_eq] at h\n  norm_num at h\n  convert h using 1\n  ring",
    "have hf := (hasDerivAt_id _).const_mul _\n  have hg := Real.hasDerivAt_cos _\n  have h := hg.comp _ hf\n  simp only [Function.comp, id_eq] at h\n  norm_num at h\n  convert h using 1\n  ring",
    "have hf := (hasDerivAt_id _).const_mul _\n  have hg := Real.hasDerivAt_sin _\n  have h := hg.comp _ hf\n  simp only [Function.comp, id_eq, mul_one] at h\n  convert h using 1\n  ring",
    "have hf := (hasDerivAt_id _).const_mul _\n  have hg := Real.hasDerivAt_cos _\n  have h := hg.comp _ hf\n  simp only [Function.comp, id_eq, mul_one] at h\n  convert h using 1\n  ring",
    # identity and constant
    "exact hasDerivAt_id _",
    "exact hasDerivAt_const _ _",
]

# Finset.card goals where the filter is an image of a simpler set.
# Generalizable: for filter(pred, range(k*n)).card = n, express as image(f, range n)
# then use card_image_of_injective + simp [Finset.card_range].
# omega handles the membership arithmetic after simp reduces it to linear facts.
FINSET_CARD_TEMPLATES = [
    # Even filter: {k < 2n | k%2=0}.card = n  ←  bijection k↦2k
    # rw [h, card_image_of_injective] leaves (range n).card = n, closed by simp.
    "have h : (Finset.range (2 * n)).filter (fun k => k % 2 = 0) = (Finset.range n).image (2 * ·) := by\n    ext k\n    simp only [Finset.mem_filter, Finset.mem_range, Finset.mem_image]\n    constructor\n    · intro ⟨hk, hmod⟩; exact ⟨k / 2, by omega, by omega⟩\n    · rintro ⟨m, hm, rfl⟩; exact ⟨by omega, by omega⟩\n  rw [h, Finset.card_image_of_injective _ (fun a b hab => by omega)]\n  simp",
    "have h : (Finset.range (2 * n)).filter (fun k => k % 2 = 0) = (Finset.range n).image (· * 2) := by\n    ext k\n    simp only [Finset.mem_filter, Finset.mem_range, Finset.mem_image]\n    constructor\n    · intro ⟨hk, hmod⟩; exact ⟨k / 2, by omega, by omega⟩\n    · rintro ⟨m, hm, rfl⟩; exact ⟨by omega, by omega⟩\n  rw [h, Finset.card_image_of_injective _ (fun a b hab => by omega)]\n  simp",
    # Odd filter: {k < 2n | k%2≠0}.card = n  ←  bijection k↦2k+1
    "have h : (Finset.range (2 * n)).filter (fun k => k % 2 ≠ 0) = (Finset.range n).image (2 * · + 1) := by\n    ext k\n    simp only [Finset.mem_filter, Finset.mem_range, Finset.mem_image]\n    constructor\n    · intro ⟨hk, hmod⟩; exact ⟨k / 2, by omega, by omega⟩\n    · rintro ⟨m, hm, rfl⟩; exact ⟨by omega, by omega⟩\n  rw [h, Finset.card_image_of_injective _ (fun a b hab => by omega)]\n  simp",
]

# Fintype / Pigeonhole templates (tried in cmd mode before BFS)
# Generalizable: Fintype.exists_ne_map_eq_of_card_lt is the standard Mathlib Pigeonhole lemma;
# simp [Fintype.card_fin] reduces Fintype.card (Fin n) → n; omega closes the card inequality.
FINTYPE_TEMPLATES = [
    "apply Fintype.exists_ne_map_eq_of_card_lt\n  simp [Fintype.card_fin, *]",
    "apply Fintype.exists_ne_map_eq_of_card_lt\n  simp [Fintype.card_fin]\n  omega",
    "apply Fintype.exists_ne_map_eq_of_card_lt\n  omega",
]

# Step-by-step tactics used in iterative BFS search
STEP_TACTICS = [
    # Intro / elimination
    "intro h", "intro hp hq", "intro hp hq hr",
    "exact h", "exact hp", "exact hq", "exact hr",
    "apply h", "apply hp", "apply hq",
    "assumption",
    # Structural
    "constructor", "left", "right",
    "rcases h with ha | hb",
    "obtain ⟨a, b⟩ := h",
    # Auto closers
    "tauto", "simp", "ring", "omega", "norm_num", "linarith", "aesop",
    "fun_prop", "norm_cast",
    # Derivative building blocks (for BFS multi-step)
    "apply HasDerivAt.const_mul", "apply HasDerivAt.comp",
    "apply HasDerivAt.neg", "apply HasDerivAt.add",
    "exact Real.hasDerivAt_sin _", "exact Real.hasDerivAt_cos _",
    "exact hasDerivAt_id _",
    # Inner product / norm lemmas
    "exact real_inner_comm _ _", "exact inner_add_left _ _ _",
    "exact inner_self_eq_zero", "exact norm_smul _ _",
    "simp [inner_smul_left]", "simp [real_inner_self_eq_norm_sq]",
    "simp [EuclideanSpace.inner_single_left]", "simp [EuclideanSpace.norm_single]",
    # Complex
    "simp [normSq_apply, sq]", "congr 1",
    # Fintype / Pigeonhole principle (standard Mathlib lemma for ∃-collision goals)
    "apply Fintype.exists_ne_map_eq_of_card_lt",
    # Fintype.card simp rules (reduces Fintype.card (Fin n) to n)
    "simp [Fintype.card_fin]", "simp [Fintype.card_fin, *]",
]

# Max seconds per theorem for iterative proof search
STEP_TIME_LIMIT = 10
DEFAULT_THEOREM_TIMEOUT = 60

def select_tactics(goal: str) -> list:
    """Narrow the tactic list based on symbols in the goal string."""
    # Inner product space goals: inner (𝕜 := ℝ), @inner ℝ, or ⟪x,y⟫_ℝ notation
    if (re.search(r'\binner\b', goal) and ("ℝ" in goal or "𝕜" in goal)) or "⟪" in goal:
        return INNER_PRODUCT_TACTICS + SEARCH_TACTICS
    # Norm + smul: ‖c • x‖ type goals
    if "‖" in goal and "•" in goal:
        return ["exact norm_smul _ _", "simp [norm_smul]"] + INNER_PRODUCT_TACTICS + SEARCH_TACTICS
    # Complex normSq goals
    if "normSq" in goal:
        return COMPLEX_TACTICS + SEARCH_TACTICS
    # Complex exponential goals: exp(...)^n = exp(...) — de Moivre type
    # open Complex 環境では "Complex" がゴールに現れないため、exp + I の組み合わせでも検出
    if "exp" in goal and re.search(r'\^\s*\w+', goal) and ("Complex" in goal or "ℂ" in goal or re.search(r'\bI\b', goal)):
        return COMPLEX_TACTICS + SEARCH_TACTICS
    # HasDerivAt / HasFDerivAt: must come before trig check because HasDerivAt goals
    # often contain "sin"/"cos" and "=>" (lambda), making "=" in goal True spuriously.
    if "HasDerivAt" in goal or "HasFDerivAt" in goal:
        chain_tactics = chain_rule_deriv_tactics(goal)
        return chain_tactics + DERIV_TEMPLATES + ["fun_prop", "simp"] + SEARCH_TACTICS
    if "Continuous" in goal or "Differentiable" in goal:
        return ["fun_prop", "simp", "aesop"] + SEARCH_TACTICS
    # Trig double-angle goals: cos_two_mul / sin_sq_add_cos_sq が必要なゴール
    # "cos" と "sin" が両方あり等式・不等式を含む場合のみ発火
    # "=" in goal は lambda "=>" も引っかかるため、⊢ 以降で "=>" 以外の "=" か "≤" を検索する
    if "cos" in goal and "sin" in goal and (
        "≤" in goal or re.search(r'⊢[^\n]*(?<!=)=(?![>=])', goal)
    ):
        return TRIG_DOUBLE_TACTICS + SIMPLE_TACTICS + SEARCH_TACTICS
    if "∑" in goal or "Finset" in goal:
        # card goals: try bijection-based templates before induction
        if ".card" in goal:
            return FINSET_CARD_TEMPLATES + INDUCTION_TACTICS + SEARCH_TACTICS
        return INDUCTION_TACTICS + SEARCH_TACTICS
    if "Irrational" in goal:
        return SEARCH_TACTICS
    # ∃-collision goals over Fin types (e.g. Pigeonhole principle)
    if "∃" in goal and "Fin" in goal:
        return FINTYPE_TEMPLATES + SEARCH_TACTICS
    # Factorial + prime goals (Wilson's theorem pattern).
    # Detected by '!' in goal (open scoped Nat renders n! not Nat.factorial)
    # combined with Nat.Prime in context (avoids false positives on other ! uses).
    # Variable names are extracted dynamically so any naming convention works.
    if "!" in goal and "Nat.Prime" in goal:
        m = re.search(r'(\w+)\s*:\s*Nat\.Prime\s+(\w+)', goal)
        if m:
            hname, pvar = m.group(1), m.group(2)
            return [
                f"haveI : Fact (Nat.Prime {pvar}) := ⟨{hname}⟩\n  exact ZMod.wilsons_lemma {pvar}",
                f"haveI : Fact (Nat.Prime {pvar}) := ⟨{hname}⟩\n  simp [ZMod.wilsons_lemma]",
            ] + SEARCH_TACTICS
    # ZMod goals: skip simple tactics that can't possibly work and go to search.
    if "ZMod" in goal:
        return ["norm_cast", "push_cast; ring", "simp"] + SEARCH_TACTICS
    # Polynomial inequality goals (≤ or ≥ with ^): build dynamic nlinarith witnesses.
    # nonneg3: for 3-var non-neg goals (AM-GM3, cube AM-GM, …)
    # pairwise_sq: for goals without non-neg assumptions (Cauchy-Schwarz, sym-ineq, …)
    if ("≤" in goal or "≥" in goal) and "^" in goal:
        tactics: list[str] = []
        nonneg_tac = nlinarith_nonneg3_tactic(goal)
        pairwise_tac = nlinarith_pairwise_sq_tactic(goal)
        if nonneg_tac:
            tactics += [nonneg_tac, "field_simp\n  " + nonneg_tac]
        if pairwise_tac:
            tactics.append(pairwise_tac)
        if tactics:
            return tactics + ["ring", "nlinarith", "linarith"] + SEARCH_TACTICS
    if "^" in goal:
        return ["ring", "nlinarith", "norm_num"] + INDUCTION_TACTICS + SEARCH_TACTICS
    if "ℝ" in goal or "ℚ" in goal:
        return ["ring", "linarith", "norm_num", "nlinarith", "fun_prop"] + SEARCH_TACTICS
    if "ℕ" in goal or "ℤ" in goal:
        return ["omega", "simp", "rfl", "decide", "ring", "norm_num", "norm_cast"] + SEARCH_TACTICS
    return ALL_TACTICS + SEARCH_TACTICS

# ────────────────────────────────────────────────
# Utilities
# ────────────────────────────────────────────────

def has_error(resp: dict) -> bool:
    return any(m.get("severity") == "error" for m in resp.get("messages", []))


def format_repl_errors(resp: dict) -> str:
    parts = []
    for msg in resp.get("messages", []):
        if msg.get("severity") == "error":
            data = msg.get("data", "").strip()
            if data:
                parts.append(data)
    return "\n".join(parts)

def prove_iterative(session, example: str, base_env: int, time_limit: int = STEP_TIME_LIMIT,
                    deadline: float | None = None) -> str | None:
    """BFS proof search: apply one tactic at a time via REPL tactic mode.

    Sends {"tactic": t, "proofState": N} to step through a proof incrementally.
    Returns a newline-joined tactic sequence on success, or None on timeout/failure.
    """
    # Obtain initial proof state from sorry
    resp = session.send({"cmd": f"{example} := by sorry", "env": base_env})
    sorries = resp.get("sorries", [])
    if not sorries:
        return None
    init_state = sorries[0].get("proofState")
    if init_state is None:
        return None

    phase_deadline = time.time() + time_limit
    if deadline is not None:
        phase_deadline = min(phase_deadline, deadline)
    # BFS: each entry is (proof_state_id, tactics_applied_so_far)
    queue: deque[tuple[int, list[str]]] = deque([(init_state, [])])
    visited: set[int] = set()

    while queue and time.time() < phase_deadline:
        state, applied = queue.popleft()
        if len(applied) >= 6 or state in visited:
            continue
        visited.add(state)

        for t in STEP_TACTICS:
            if time.time() > phase_deadline:
                return None
            resp = session.send({"tactic": t, "proofState": state})
            if has_error(resp):
                continue
            # Use get() without default: absent key → None (avoids {} false-positive)
            goals = resp.get("goals")
            new_state = resp.get("proofState")
            if goals is None and new_state is None:
                continue  # REPL returned empty / didn't recognise the command
            new_applied = applied + [t]
            if goals == []:          # all goals closed — proof complete
                return "\n".join(new_applied)
            if new_state is not None and goals is not None and len(goals) <= 4:
                queue.append((new_state, new_applied))

    return None

def extract_try_this(resp: dict) -> str | None:
    """Extract the concrete tactic from 'Try this:' messages (exact? / simp? output).

    Handles both single-line ('Try this: exact X') and multi-line formats
    ('Try this:\\n  [apply] exact X') produced by different Lean/Mathlib versions.
    """
    for msg in resp.get("messages", []):
        data = msg.get("data", "")
        # Try this: exact X  (single-line)
        # Try this:\n  [apply] exact X  (multi-line with optional tag)
        m = re.search(r"Try this:[ \t]*\n?[ \t]*(?:\[\w+\] )?(.+)", data)
        if m:
            return m.group(1).strip()
    return None


def goal_has_symmetric_target(goal: str) -> bool:
    """Whether the goal target looks like an equality/iff where `.symm` may help."""
    target_lines = [line for line in goal.splitlines() if "⊢" in line]
    if not target_lines:
        return False
    target = target_lines[-1]
    return " = " in target or " ↔ " in target


def search_suggestion_variants(suggestion: str, goal: str) -> list[str]:
    """Expand `Try this:` suggestions into a few proof variants to verify.

    `exact?` often finds the right lemma body, but not always in the exact
    orientation or simplification form needed by the goal.  We keep the raw
    suggestion first, then try light wrappers such as `simpa using ...` and
    `.symm` for equality / iff goals.
    """
    variants: list[str] = []

    def add_variant(tactic: str):
        if tactic not in variants:
            variants.append(tactic)

    add_variant(suggestion)

    if suggestion.startswith("exact "):
        expr = suggestion[len("exact "):].strip()
        if expr:
            add_variant(f"simpa using {expr}")
            if goal_has_symmetric_target(goal):
                symm_expr = f"({expr}).symm"
                add_variant(f"exact {symm_expr}")
                add_variant(f"simpa using {symm_expr}")

    return variants


def verify_tactic_variants(session, example: str, base_env: int,
                           tactics: list[str], prefix: str = "") -> str | None:
    """Return the first tactic variant that fully proves the example."""
    for tactic in tactics:
        body = f"{prefix}{tactic}" if prefix else tactic
        resp = session.send({"cmd": f"{example} := by\n  {body}", "env": base_env})
        if not has_error(resp):
            return body
    return None

def to_example(stmt: str) -> str:
    return re.sub(r"^theorem\s+\S+", "example", stmt)

def extract_nonneg_triples(goal: str) -> list[tuple[str, str]]:
    """Extract (hypothesis, variable) pairs from '0 ≤ var' in the proof state.

    Used to build generalizable nlinarith witnesses for polynomial inequalities
    with non-negativity assumptions (AM-GM, Cauchy-Schwarz, etc.).
    Returns pairs in order of appearance, e.g. [('ha','a'), ('hb','b'), ('hc','c')].
    """
    return re.findall(r'(\w+)\s*:\s*0\s*≤\s*(\w+)', goal)

def extract_chain_rule_params(goal: str) -> tuple[str, str, str] | None:
    """Extract (trig_fn, coeff, point) from a HasDerivAt chain rule goal.

    Matches: HasDerivAt (fun x => Real.F (c * x)) (... Real.F' (c * pt)) pt
    Returns e.g. ('sin', '2', 'a') for the bench_hard_chain goal.
    Used to build fully explicit .comp templates that avoid implicit-arg inference errors.
    """
    m = re.search(r'HasDerivAt \(fun \w+ => Real\.(sin|cos|exp) \((\S+) \* \w+\)\)', goal)
    if not m:
        return None
    fn = m.group(1)
    coeff = m.group(2)
    # point is the last token on the ⊢ line
    goal_line = [l for l in goal.splitlines() if "⊢" in l]
    if not goal_line:
        return None
    pt = goal_line[0].split()[-1]
    return fn, coeff, pt

def chain_rule_deriv_tactics(goal: str) -> list[str]:
    """Build explicit HasDerivAt chain rule tactic strings.

    Returns [] if the goal doesn't match the linear-composition pattern.
    Generates templates with all arguments explicit to avoid .comp implicit-arg failures.
    Pattern: HasDerivAt (fun x => Real.F(c*x)) (c * Real.F'(c*pt)) pt
    """
    p = extract_chain_rule_params(goal)
    if not p:
        return []
    fn, coeff, pt = p
    inner = f"({coeff} * {pt})"
    base = f"(Real.hasDerivAt_{fn} {inner}).comp {pt} ((hasDerivAt_id {pt}).const_mul {coeff})"
    deriv_map = {
        "sin": f"Real.cos {inner}",
        "cos": f"-Real.sin {inner}",
        "exp": f"Real.exp {inner}",
    }
    deriv = deriv_map[fn]
    return [
        (
            f"have hf : HasDerivAt (fun x => {coeff} * x) {coeff} {pt} := by\n"
            f"    simpa using (hasDerivAt_id {pt}).const_mul {coeff}\n"
            f"  have hg : HasDerivAt Real.{fn} ({deriv}) {inner} :=\n"
            f"    Real.hasDerivAt_{fn} {inner}\n"
            f"  have h := hg.comp {pt} hf\n"
            f"  convert h using 1\n"
            f"  ring"
        ),
        # id_eq (not bare `id`) is the correct simp lemma for `id x = x` in Lean 4
        f"have h := {base}\n  simp only [Function.comp, id_eq, mul_one] at h\n  convert h using 1\n  ring",
        # ring_nf normalises both sides to the same form before exact
        f"have h := {base}\n  simp only [Function.comp, id_eq, mul_one, mul_comm] at h\n  exact h",
        # fallback: skip simp and rely on convert depth-1 + ring
        f"have h := {base}\n  convert h using 1\n  ring",
    ]

def extract_real_vars(goal: str) -> list[str]:
    """Extract variable names declared as ℝ or ℚ in the proof state context.

    e.g. 'a b : ℝ' → ['a', 'b']; 'a b c d : ℝ' → ['a', 'b', 'c', 'd']
    """
    result, seen = [], set()
    for m in re.finditer(r'(\b\w+(?:\s+\w+)*)\s*:\s*[ℝℚ]', goal):
        for name in m.group(1).split():
            if name not in seen:
                seen.add(name)
                result.append(name)
    return result

def nlinarith_pairwise_sq_tactic(goal: str) -> str | None:
    """Generate nlinarith witnesses from pairwise squared differences of ℝ variables.

    Handles polynomial inequalities WITHOUT explicit non-negativity assumptions.
    Witness pattern:
      - sq_nonneg (vi - vj)  for every pair  →  covers a²+b²+c² ≥ ab+bc+ca, (a+b+c)²≤3(a²+b²+c²)
      - sq_nonneg (vi*vk - vj*vl) for 4-var  →  covers 2D Cauchy-Schwarz (ad-bc)²≥0
    """
    vs = extract_real_vars(goal)
    if len(vs) < 2:
        return None
    witnesses = [f"sq_nonneg ({vs[i]} - {vs[j]})"
                 for i in range(len(vs)) for j in range(i + 1, len(vs))]
    if len(vs) >= 4:
        a, b, c, d = vs[0], vs[1], vs[2], vs[3]
        witnesses.append(f"sq_nonneg ({a}*{d} - {b}*{c})")
    return "nlinarith [" + ", ".join(witnesses) + "]"

def nlinarith_nonneg3_tactic(goal: str) -> str | None:
    """Build a generalizable nlinarith witness tactic for 3-variable non-negative ℝ inequalities.

    For goals like 'a*b*c ≤ ((a+b+c)/3)^3' with 'ha:0≤a', 'hb:0≤b', 'hc:0≤c',
    generates witnesses: pairwise squared differences + their products with non-neg vars.
    This covers AM-GM (3-var) and related symmetric polynomial inequalities.
    Returns None if fewer than 3 non-neg hypotheses are found.
    """
    pairs = extract_nonneg_triples(goal)
    if len(pairs) < 3:
        return None
    (h1, v1), (h2, v2), (h3, v3) = pairs[0], pairs[1], pairs[2]
    witnesses = [
        f"sq_nonneg ({v1} - {v2})",
        f"sq_nonneg ({v2} - {v3})",
        f"sq_nonneg ({v1} - {v3})",
        f"mul_nonneg {h1} (sq_nonneg ({v2} - {v3}))",
        f"mul_nonneg {h2} (sq_nonneg ({v1} - {v3}))",
        f"mul_nonneg {h3} (sq_nonneg ({v1} - {v2}))",
        f"mul_nonneg (mul_nonneg {h1} {h2}) {h3}",
    ]
    return "nlinarith [" + ", ".join(witnesses) + "]"

def have_candidates(goal: str) -> list[str]:
    """Generate 'have h := ...' lines from proof-state goal structure.

    Each returned string is a single have-tactic line that can be prepended
    before a closing tactic.  Patterns covered:
      - h : X ≠ 0  →  have h2 : X ^ 2 ≠ 0 := pow_ne_zero 2 h
      - sin/cos present  →  have := sin_sq_add_cos_sq var
      - ha : 0 < x  →  have ha' : 0 ≤ x := le_of_lt ha
      - sq_nonneg witnesses for ℝ inequality goals
    """
    candidates = []

    # 1. h : expr ≠ 0  →  expr ^ 2 ≠ 0  (enables field_simp [h2])
    for m in re.finditer(r'(\w+)\s*:\s*(\w+(?:\s+\w+)?)\s*≠\s*0', goal):
        hname = m.group(1)
        expr = m.group(2).strip()
        # Only single-token expressions (e.g. "cos x" → skip, "hx" → take expr=token before ≠)
        # Actually goal format: "hx : cos x ≠ 0" → expr = "cos x"  (multi-token)
        # We want the full expression; pow_ne_zero expects a proof of the base ≠ 0.
        # Simple heuristic: wrap expr in parens if it contains a space.
        expr_lean = f"({expr})" if " " in expr else expr
        candidates.append(
            f"have {hname}2 : {expr_lean} ^ 2 ≠ 0 := pow_ne_zero 2 {hname}"
        )

    # 2. sin/cos in goal  →  pythagorean identity
    if "sin" in goal or "cos" in goal:
        seen: set[str] = set()
        for m in re.finditer(r'(?:sin|cos)\s+(\w+)', goal):
            v = m.group(1)
            if v not in seen:
                seen.add(v)
                candidates.append(f"have hsc_{v} := sin_sq_add_cos_sq {v}")
                candidates.append(f"have hsc_{v} := Real.sin_sq_add_cos_sq {v}")

    # 3. ha : 0 < x  →  have : 0 ≤ x
    for m in re.finditer(r'(\w+)\s*:\s*0\s*<\s*(\w+)', goal):
        hname, var = m.group(1), m.group(2)
        candidates.append(f"have {hname}' : 0 ≤ {var} := le_of_lt {hname}")

    # 4. sq_nonneg pairwise witnesses for ℝ inequality goals
    if "≤" in goal or "≥" in goal or "<" in goal or ">" in goal:
        vs = extract_real_vars(goal)
        for i in range(min(len(vs), 3)):
            for j in range(i + 1, min(len(vs), 3)):
                candidates.append(f"have hnn_{i}{j} := sq_nonneg ({vs[i]} - {vs[j]})")

    return candidates


def have_closers(have_line: str, remaining_goal: str) -> list[str]:
    """Build closer tactics to try after a have-prefix, ordered by likelihood."""
    m = re.match(r'have\s+(\w+)\b', have_line)
    name = m.group(1) if m else None

    # Generic closers first
    closers = ["ring", "linarith", "nlinarith", "simp", "omega",
               "field_simp; ring", "field_simp; linarith",
               "field_simp; nlinarith", "simp_all"]

    # Name-aware closers: use the introduced hypothesis directly
    if name:
        closers = [
            f"field_simp [{name}]; ring",
            f"field_simp [{name}]; linarith",
            f"field_simp [{name}]; nlinarith",
            f"simp [{name}]",
            f"linarith [{name}]",
            f"nlinarith [{name}]",
            f"nlinarith [{name}, sq_nonneg _]",
        ] + closers

    # Append goal-selected closers for the remaining goal
    closers += select_tactics(remaining_goal)[:8]
    return closers


def prove_with_have(session, example: str, base_env: int,
                   have_line: str, deadline: float | None = None) -> str | None:
    """Try to prove example by injecting have_line then closing the remainder.

    1. Sends 'example := by  have_line  sorry' to obtain the remaining goal.
    2. Generates closers from that remaining goal.
    3. Tries each closer until one succeeds.
    Returns the full tactic string on success, None otherwise.
    """
    # Step 1: validate the have and extract remaining goal
    if deadline is not None and time.monotonic() >= deadline:
        return None
    probe = session.send({"cmd": f"{example} := by\n  {have_line}\n  sorry",
                          "env": base_env})
    if has_error(probe):
        return None
    sorries = probe.get("sorries", [])
    if not sorries:
        # have alone closed the goal (unexpected but valid)
        return have_line
    remaining_goal = sorries[0].get("goal", "")

    # Step 2: try each closer
    for closer in have_closers(have_line, remaining_goal):
        if deadline is not None and time.monotonic() >= deadline:
            return None
        resp = session.send(
            {"cmd": f"{example} := by\n  {have_line}\n  {closer}", "env": base_env}
        )
        if not has_error(resp):
            return f"{have_line}\n  {closer}"
    return None


def fact_preamble(stmt: str) -> str:
    """Generate haveI lines for Nat.Prime hypotheses.

    e.g. '(hp : Nat.Prime p)' → 'haveI : Fact (Nat.Prime p) := ⟨hp⟩'
    Many Mathlib lemmas (ZMod.wilsons_lemma, ZMod.pow_card, …) require
    [Fact (Nat.Prime p)] as a typeclass, so this bridges the gap between
    a plain hypothesis and the typeclass the lemma expects.
    """
    lines = []
    for m in re.finditer(r'\((\w+)\s*:\s*Nat\.Prime\s+(\w+)\)', stmt):
        hname, pvar = m.group(1), m.group(2)
        lines.append(f"haveI : Fact (Nat.Prime {pvar}) := ⟨{hname}⟩")
    return "\n  ".join(lines)

# ────────────────────────────────────────────────
# Automated proving
# ────────────────────────────────────────────────

def prove_all(theorems: list, dry_run: bool = False, preamble: str = "",
              skip_phase17: bool = False, use_proved: bool = False,
              theorem_timeout: int | None = DEFAULT_THEOREM_TIMEOUT,
              session: ReplSession | None = None, base_env: int | None = None) -> list:
    """Attempt to prove each theorem.

    dry_run=True: skip ProvedTheorems.lean writes and cache updates (used by benchmark.py
    so that one run cannot contaminate the next).
    skip_phase17=True: bypass Phase 1.7 (used by A/B coverage tests).
    use_proved=True: import LeanMathAtlas.ProvedTheorems into the REPL so previously
    proved theorems are available as lemmas during proof search.
    theorem_timeout: total per-theorem time budget in seconds across all phases.
    session/base_env: optional preloaded proof environment to reuse across calls.
    """
    index = load_index()
    uncached = theorems if dry_run else [
        s for s in theorems
        if ensured_proof_entry(index.get(cache_key(s))) is None
    ]

    new_results: dict[str, tuple] = {}

    if uncached:
        owns_session = session is None or base_env is None
        if owns_session:
            session, base_env = prepare_proof_env(dry_run=dry_run, preamble=preamble, use_proved=use_proved)
        try:
            for stmt in uncached:
                example = to_example(stmt)
                t_stmt = time.monotonic()
                theorem_deadline = None if theorem_timeout is None else t_stmt + theorem_timeout

                def timed_out() -> bool:
                    return theorem_deadline is not None and time.monotonic() >= theorem_deadline

                # Fetch the goal
                goal = ""
                resp = session.send({"cmd": f"{example} := by sorry", "env": base_env})
                sorries = resp.get("sorries", [])
                if sorries:
                    goal = sorries[0].get("goal", "")

                # Phase 1: try each filtered tactic in one shot
                proof = None
                for t in select_tactics(goal):
                    if timed_out():
                        break
                    resp = session.send({"cmd": f"{example} := by\n  {t}", "env": base_env})
                    if not has_error(resp):
                        if t in SEARCH_TACTICS:
                            extracted = extract_try_this(resp)
                            if extracted is None:
                                continue
                            proof = extracted
                        else:
                            proof = t
                        if not dry_run:
                            lean_name = lean_name_from(stmt)
                            persist_proof(stmt, proof, goal, lean_name, preamble, index, use_proved)
                        break
                    if t in SEARCH_TACTICS:
                        extracted = extract_try_this(resp)
                        if extracted is None:
                            continue
                        verified = verify_tactic_variants(
                            session, example, base_env,
                            search_suggestion_variants(extracted, goal),
                        )
                        if verified is None:
                            continue
                        proof = verified
                        if not dry_run:
                            lean_name = lean_name_from(stmt)
                            persist_proof(stmt, proof, goal, lean_name, preamble, index, use_proved)
                        break

                # Phase 1.5: Fact typeclass preamble + tactics
                # Handles lemmas that require [Fact (Nat.Prime p)] typeclass.
                # Tries SIMPLE_TACTICS first (simp/norm_num may find the goal if the target
                # lemma is @[simp]), then SEARCH_TACTICS as fallback.
                # For search tactics (exact?/simp?), we extract the "Try this:" suggestion even
                # if the response has errors (exact? may report an error while still suggesting
                # the right lemma), then verify the suggestion in a separate REPL call.
                if proof is None:
                    fact_block = fact_preamble(stmt)
                    if fact_block:
                        # Preprocessing variants: try cast normalisation before search tactics.
                        # norm_cast / push_cast can reveal ZMod.wilsons_lemma and similar
                        # lemmas that exact? misses when the goal has coercion noise.
                        _cast_prefixes = ["", "norm_cast\n  ", "push_cast\n  "]
                        _phase15_tactics = SIMPLE_TACTICS + SEARCH_TACTICS
                        for _cast in _cast_prefixes:
                            if proof is not None:
                                break
                            for t in _phase15_tactics:
                                if timed_out():
                                    break
                                resp = session.send({
                                    "cmd": f"{example} := by\n  {fact_block}\n  {_cast}{t}",
                                    "env": base_env
                                })
                                if t in SEARCH_TACTICS:
                                    # Extract suggestion regardless of errors, then verify separately
                                    extracted = extract_try_this(resp)
                                    if extracted:
                                        if timed_out():
                                            break
                                        verified = verify_tactic_variants(
                                            session, example, base_env,
                                            search_suggestion_variants(extracted, goal),
                                            prefix=f"{fact_block}\n  {_cast}",
                                        )
                                        if verified is not None:
                                            proof = verified
                                            if not dry_run:
                                                lean_name = lean_name_from(stmt)
                                                persist_proof(stmt, proof, goal, lean_name, preamble, index, use_proved)
                                            break
                                elif not has_error(resp):
                                    proof = f"{fact_block}\n  {_cast}{t}"
                                    if not dry_run:
                                        lean_name = lean_name_from(stmt)
                                        persist_proof(stmt, proof, goal, lean_name, preamble, index, use_proved)
                                    break

                # Phase 1.6: apply? + all_goals closer
                # apply? finds any Mathlib lemma that partially matches the goal,
                # then closes remaining subgoals with standard tactics.
                # More powerful than exact? for goals that need a lemma application
                # followed by a simple finishing step (e.g. Pigeonhole + card simp).
                if proof is None:
                    _closers = [
                        "simp", "simp [*]", "omega",
                        "simp [Fintype.card_fin, *]", "simp_all",
                    ]
                    # Try plain apply? first, then with Fact preamble if present
                    _preamble = fact_preamble(stmt)
                    _prefixes = [""]
                    if _preamble:
                        _prefixes.append(_preamble)
                    for _pre in _prefixes:
                        if proof is not None:
                            break
                        if timed_out():
                            break
                        _pre_block = f"  {_pre}\n  " if _pre else "  "
                        _resp = session.send({
                            "cmd": f"{example} := by\n{_pre_block}apply?",
                            "env": base_env
                        })
                        _sug = extract_try_this(_resp)
                        if not _sug or not (_sug.startswith("apply ") or _sug.startswith("refine ")):
                            continue
                        for _closer in _closers:
                            if timed_out():
                                break
                            _cmd = (
                                f"{example} := by\n  {_pre}\n  {_sug}\n  all_goals {_closer}"
                                if _pre else
                                f"{example} := by\n  {_sug}\n  all_goals {_closer}"
                            )
                            _resp2 = session.send({"cmd": _cmd, "env": base_env})
                            if not has_error(_resp2):
                                proof = (
                                    f"{_pre}\n  {_sug}\n  all_goals {_closer}"
                                    if _pre else
                                    f"{_sug}\n  all_goals {_closer}"
                                )
                                if not dry_run:
                                    lean_name = lean_name_from(stmt)
                                    persist_proof(stmt, proof, goal, lean_name, preamble, index, use_proved)
                                break

                # Phase 2: if one-shot failed, try iterative BFS (time-limited)
                if proof is None and not timed_out():
                    remaining = None if theorem_deadline is None else max(0.0, theorem_deadline - time.monotonic())
                    phase_limit = STEP_TIME_LIMIT if remaining is None else min(STEP_TIME_LIMIT, remaining)
                    print(f"  [step] iterative search (up to {phase_limit:.0f}s)...")
                    step_proof = prove_iterative(session, example, base_env, time_limit=max(1, int(phase_limit)),
                                                 deadline=theorem_deadline)
                    if step_proof:
                        proof = step_proof
                        if not dry_run:
                            lean_name = lean_name_from(stmt)
                            persist_proof(stmt, proof, goal, lean_name, preamble, index, use_proved)

                # Phase 3 (last resort): have-augmented proofs
                # Tried after BFS because it costs O(candidates × closers) REPL calls.
                # Covers theorems needing one intermediate fact that neither one-shot
                # tactics nor BFS can construct (e.g. sin²+cos²=1 for single-trig goals).
                if proof is None and not skip_phase17 and not timed_out():
                    for have_line in have_candidates(goal):
                        if timed_out():
                            break
                        p = prove_with_have(session, example, base_env, have_line, theorem_deadline)
                        if p:
                            proof = p
                            if not dry_run:
                                lean_name = lean_name_from(stmt)
                                persist_proof(stmt, proof, goal, lean_name, preamble, index, use_proved)
                            break

                if proof is None and timed_out():
                    print(f"  [timeout] theorem budget exceeded ({theorem_timeout}s)")

                new_results[stmt] = (proof, goal, time.monotonic() - t_stmt)

        finally:
            if owns_session:
                session.close()
            if not dry_run:
                save_index(index)

    # Collect results in the original order
    results = []
    for stmt in theorems:
        if stmt in new_results:
            proof, goal, solve_time = new_results[stmt]
        else:
            lean_name = ensured_proof_entry(index.get(cache_key(stmt))) or ""
            proof = lean_name  # already proved — return the Lean name
            goal = ""
            solve_time = 0.0
        results.append((stmt, proof, goal, solve_time))
    return results

# ────────────────────────────────────────────────
# Test theorems
# ────────────────────────────────────────────────

TESTS = [
    "theorem t1 : (1:ℕ) + 1 = 2",
    "theorem t2 (n : ℕ) : n + 0 = n",
    "theorem t3 (a b : ℤ) : a + b = b + a",
    "theorem t4 (a b : ℝ) : (a + b)^2 = a^2 + 2*a*b + b^2",
    "theorem t5 (a b c : ℕ) : (a + b) + c = a + (b + c)",
    "theorem t6 (n : ℕ) : 2 * ∑ k ∈ Finset.range (n + 1), k = n * (n + 1)",
    "theorem t7 (n : ℕ) : 6 * ∑ k ∈ Finset.range (n + 1), k ^ 2 = n * (n + 1) * (2 * n + 1)",
]

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", type=Path, help="source .lean file to extract preamble from")
    parser.add_argument("--use-proved", action="store_true",
                        help="import previously proved theorems into the REPL during proof search")
    parser.add_argument("--theorem-timeout", type=int, default=DEFAULT_THEOREM_TIMEOUT,
                        help="total per-theorem timeout in seconds across all proof phases")
    parser.add_argument("theorems", nargs="*")
    args = parser.parse_args()

    targets = args.theorems if args.theorems else TESTS
    preamble = extract_preamble(args.file) if args.file else ""
    if preamble:
        print(f"[preamble] {preamble!r}")

    index = load_index()
    cached_count = sum(1 for s in targets if ensured_proof_entry(index.get(cache_key(s))) is not None)
    print(f"[run] {len(targets)} theorems ({cached_count} cached / {len(targets) - cached_count} uncached)")

    t0 = time.time()
    try:
        results = prove_all(
            targets,
            preamble=preamble,
            use_proved=args.use_proved,
            theorem_timeout=args.theorem_timeout,
        )
    except RuntimeError as err:
        print(f"[error] {err}")
        sys.exit(1)
    elapsed = time.time() - t0

    passed = failed = 0
    for stmt, proof, goal, solve_time in results:
        print(f"\n{'─'*60}")
        print(f"target: {stmt}")
        if goal:
            print(f"  goal: {goal}")
        if proof:
            proof_display = "\n    ".join(proof.split("\n"))
            print(f"  ✓ by\n    {proof_display}")
            passed += 1
        else:
            print(f"  ✗ proof not found")
            failed += 1

    print(f"\n{'─'*60}")
    print(f"total: {passed} passed / {failed} failed / {elapsed:.1f}s")
    if passed > 0:
        print(f"  → saved to {AUTO_PROVED_DIR.relative_to(WORKDIR)}/ + {LEAN_DB_FILE.relative_to(WORKDIR)}")

if __name__ == "__main__":
    main()
